### ISSUE TITLE
It does not register the service worker as there is a typo on pwabuilder-sw-register.js

### ISSUE THREAD

**Issue by ricardoserradas** [pwa-builder/pwabuilder-serviceworkers#26]
There is a typo in line 8 of pwabuilder-sw-register.js:

`navigator.serviceWorker.register('pwabuider-sw.js', {`

There is an "L" missing between "u" and "d" on "pwabuider".

After correcting it on this file, the service worker is registered sucessfully.

**Comment by ricardoserradas** [comment]
I guess that it is already corrected on source code but still not published as the website continues to serve the wrong version.

**Comment by mattwojo** [comment]
@boyofgreen - Do you know who is currently handling these issues and whether this has typo has been resolved?

**Comment by boyofgreen** [comment]
Hi Matt, seems there are two copies of these files. We are working on a website overhaul, and we'll make sure it roles out with that.  Adding @Justinwillis96 to keep me honest

**Comment by pramilgawande** [comment]
This issue is yet not resolved. Need to manually correct in the file after download.

**Comment by jgw96** [comment]
Hey everyone! Looking into this now. Im not sure how its still getting the old version.

**Comment by pramilgawande** [comment]
> Hey everyone! Looking into this now. Im not sure how its still getting the old version.

This is going to help a lot of people.

**Comment by pramilgawande** [comment]
@jgw96 This is going to save people's time.

**Comment by pramilgawande** [comment]
@jgw96 Thanks for the good work. 👍

**Comment by jgw96** [comment]
Hello all! This issue is now fixed on the preview version (https://preview.pwabuilder.com) and will be fixed on the prod site (https://pwabuilder.com) once preview is released to prod (which should be very soon at this point). Thanks everyone!
