### ISSUE TITLE
Check that navigator.serviceWorker exists?

### ISSUE THREAD

**Issue by stuartlangridge** [pwa-builder/pwabuilder-serviceworkers#27]
Looking at https://github.com/pwa-builder/serviceworkers/blob/master/serviceWorker3/pwabuilder-sw-register.js, shouldn't it be checking that `navigator.serviceWorker` exists before using it?

**Comment by jgw96** [comment]
Hello all, this is now fixed with the above PRs! Because of this I will be closing this issue for now. Thanks!
