### ISSUE TITLE
Issue of the starting pwbuilder-sw.js 

### ISSUE THREAD

**Issue by albatoy** [pwa-builder/pwabuilder-serviceworkers#39]
I run service worker pwbuilder-sw.js of 3 variant and I've got a next issue:
"pwabuilder-sw.js:1 Uncaught (in promise) TypeError: Request failed
Promise.then (async)
(anonymous) @ pwabuilder-sw.js:1
pwabuilder-sw.js:1 Uncaught (in promise) TypeError: Request failed"
here is a code:
`//This is the service worker with the combined offline experience (Offline page + Offline copy of pages)

//Install stage sets up the offline page in the cache and opens a new cache
self.addEventListener('install', function(event) {
  event.waitUntil(preLoad());
});

const preLoad = function(){
  console.log('[PWA Builder] Install Event processing');
  return caches.open('pwabuilder-offline').then(function(cache) {
    console.log('[PWA Builder] Cached index and offline page during install');
    return cache.addAll(['/offline.html', '/index.html']);
  });
};

self.addEventListener('fetch', function(event) {
  console.log('[PWA Builder] The service worker is serving the asset.');
  event.respondWith(checkResponse(event.request).catch(function() {
    return returnFromCache(event.request);}
  ));
  event.waitUntil(addToCache(event.request));
});

const checkResponse = function(request){
  return new Promise(function(fulfill, reject) {
    fetch(request).then(function(response){
      if(response.status !== 404) {
        fulfill(response);
      } else {
        reject();
      }
    }, reject);
  });
};

const addToCache = function(request){
  return caches.open('pwabuilder-offline').then(function (cache) {
    return fetch(request).then(function (response) {
      console.log('[PWA Builder] add page to offline cache: ' + response.url);
      return cache.put(request, response);
    });
  });
};

const returnFromCache = function(request){
  return caches.open('pwabuilder-offline').then(function (cache) {
    return cache.match(request).then(function (matching) {
     if(!matching || matching.status == 404) {
       return cache.match('offline.html')
     } else {
       return matching
     }
    });
  });
};`
help to solve that problem!!!

**Comment by jgw96** [comment]
Hello! It looks like you were running into this issue https://github.com/pwa-builder/pwabuilder-serviceworkers/issues/26. If you build your PWA again using `https://preview.pwabuilder.com` (will be on the production site very soon) you should not run into this issue again. Thanks!
