### ISSUE TITLE
[Workbox] Avoid using precaching without a build step

### ISSUE THREAD

**Issue by jeffposnick** [pwa-builder/pwabuilder-serviceworkers#52]
(This is in reference to the experimental code in https://github.com/pwa-builder/pwabuilder-serviceworkers/tree/workbox)

Code along the lines of https://github.com/pwa-builder/pwabuilder-serviceworkers/blob/b8a6d64f8acf8be91587fca6da1809c5232d8ce4/serviceWorker5/pwabuilder-sw.js#L13-L15

can be dangerous, in that precaching only works properly if you supply [manifest entries](https://developers.google.com/web/tools/workbox/modules/workbox-precaching#explanation_of_the_precache_list) with `url` fields that already contain versioning info (like a hash of the file's contents) or out-of-band versioning info via the `revision` field.

It's very hard to get that right when you create a precache manifest by hand, as you'd have to do with that usage, so I'd recommend not encouraging folks to do it.

If there were some way to run one of Workbox's build tools you could generate a "correct" precache manifest as a one-off, but then you'd have the problem of the manifest's entries never getting updated unless the Workbox build tool was incorporated into a local build process. I believe that's outside the intended usage for PWA Builder could offer.

**Comment by jgw96** [comment]
Yeah, i was also worried about this, thanks for bringing it up. Ill discuss with the team and see what everyone thinks.

**Comment by jgw96** [comment]
Thanks for the feedback Jeff! We ended up removing this.
