### ISSUE TITLE
[Workbox] Consider using RequestDestination for routing

### ISSUE THREAD

**Issue by jeffposnick** [pwa-builder/pwabuilder-serviceworkers#53]
(This is in reference to the experimental code in https://github.com/pwa-builder/pwabuilder-serviceworkers/tree/workbox)

One model for routing that might lend itself well to these service worker templates is to use [`RequestDestination`](https://developer.mozilla.org/en-US/docs/Web/API/RequestDestination) inside of a custom [`matchCallback`](https://developers.google.com/web/tools/workbox/guides/route-requests#matching_a_route_with_a_callback_function) to easily route different types of requests—fonts, styles, scripts, HTML documents, etc.—to different strategies. This tends to be more flexible than either hardcoding a list of URLs or path pre/suffixes.

There's a [recipe](https://developers.google.com/web/tools/workbox/guides/common-recipes#cache_resources_based_on_resource_type) for this in the Workbox docs, but it would look something like:

```
workbox.routing.registerRoute(
  ({event}) => event.request.destination === 'document',
  new workbox.strategies.NetworkFirst({
    cacheName: 'html',
    plugins: [
      new workbox.expiration.ExpirationPlugin({
        maxEntries: 10,
      }),
    ],
  })
);

workbox.routing.registerRoute(
  ({event}) => event.request.destination === 'script',
  new workbox.strategies.StaleWhileRevalidate({
    cacheName: 'javascript',
    plugins: [
      new workbox.expiration.ExpirationPlugin({
        maxEntries: 10,
      }),
    ],
  })
);

// etc., for other request types
```

You'd still need to give some thought as to what strategies to use for what types of request, and mixing in some plugins like the `ExpirationPlugin` is usually a good idea if you're not sure how large the cache might grow. But that's the general idea.

CC: @philipwalton @tomayac

**Comment by jgw96** [comment]
ohhh, really good idea. This could easily replace what i have here https://github.com/pwa-builder/pwabuilder-serviceworkers/blob/workbox/serviceWorker5/pwabuilder-sw.js , ill play with this. Thanks!

**Comment by jgw96** [comment]
Updated using this "recipe" here https://github.com/pwa-builder/pwabuilder-serviceworkers/commit/092c9e24f3bf21695d087db6b3f7320ff61349a1 . Thanks again for the feedback Jeff!
